root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/server/"
bin = "tmp/main"
full_bin = "source ./env-dev.sh && ./tmp/main"
args_bin = []
include_ext = ["go", "html"]
exclude_dir = ["data", "scripts", "tmp", "_ui"]
exclude_regex = ["_test\\.go"]
exclude_unchanged = true
follow_symlink = false
log = "air.log"
poll = false
poll_interval = 500 # ms
delay = 100 # ms
stop_on_error = true
send_interrupt = true
kill_delay = 500 # nanosecond
rerun = false
rerun_delay = 500

[log]
time = false
main_only = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = false
keep_scroll = true

# Enable live-reloading on the browser.
[proxy]
  enabled = false
  proxy_port = 8090
  app_port = 8080
