#!/bin/bash

# This script is used to launch the production (fly.io) app wrapped by the
# litestream database replicator.

# Exit build script on first failure.
set -e
# Echo commands to stdout.
set -x

echo "db url is $DB_FILE"

if [[ -f "/etc/litestream.yml" ]]; then
  echo "litestream enabled."

  # Usually for fly.io setups, we have our db file stored on a persistent
  # volume, so we only want to restore in a disaster recovery scenario.
  if [[ -f ${DB_FILE} ]]; then
    echo "db file already exists. not restoring from replica url"
  else
    echo "db file does not exist. restoring from replica url"
    litestream restore -if-replica-exists "${DB_FILE}"
  fi

  echo "running migrations"
  /atlas migrate apply --dir "file:///app/migrations" --url "sqlite://${DB_FILE}?_fk=1&_journal_mode=WAL"

  echo "starting replication"
  # Let Litestream start the server as a child process
  exec litestream replicate -exec "/app/server"
else
  echo "litestream not enabled"

  echo "running migrations"
  /atlas migrate apply --dir "file:///app/migrations" --url "sqlite://${DB_FILE}?_fk=1&_journal_mode=WAL"

  # Start server.
  eval "/app/server"
fi
