#!/bin/bash

# This script is used to launch the production (fly.io) app wrapped by the
# litestream database replicator.

# Exit build script on first failure.
set -e
# Echo commands to stdout.
set -x

echo "db url is $DB_FILE"
if [[ -f ${DB_FILE} ]]; then
  # We're seeing an issue sometimes when the db path already exists (before
  # restoration). I think it's probably in situations when we have a failed
  # deployment, and so the container had previously restored. In that case,
  # just delete the db so that the restore can succeed below.
  echo "db file already exists. removing it."
  rm -f "$DB_FILE"
fi


if [[ -n ${LITESTREAM_CONFIG_PATH} ]]; then
  echo "litestream enabled - restoring"
  # Restore database from S3.
  litestream restore -if-replica-exists "${DB_FILE}"

  echo "running migrations"
  /atlas migrate apply --dir "file:///app/migrations" --url "sqlite://${DB_FILE}?_fk=1&_journal_mode=WAL"

  echo "starting replication"
  # Let Litestream start the server as a child process
  exec litestream replicate -exec "/app/server"
else
  echo "litestream not enabled"

  echo "running migrations"
  /atlas migrate apply --dir "file:///app/migrations" --url "sqlite://${DB_FILE}?_fk=1&_journal_mode=WAL"

  # Start server.
  eval "/app/server"
fi
